### ISSUE TITLE
无法触发

### ISSUE THREAD

**Issue by SunHuawei** [yuzd/coding.net#2]
按照该文档提示，http://note.youdao.com/share/?id=1e5fdecbd76df84e7f4122f1e21e7129&type=note#/

配置完成后无法触发jenkins任务。

已经检查过下列各项：
1. coding web hook配置正确，test和push都发送成功
`13分钟前   Test    HTTP/1.1 200 OK`
`42分钟前   Push    HTTP/1.1 200 OK`
2. Jenkins中配置正确
`Trigger builds remotely (e.g., from scripts)`已开启
`Authentication Token`与coding中的`令牌`相同
3. Jenkins手动触发有效

请问，还有什么我可能忽略了的吗？如何排查问题？

**Comment by SunHuawei** [comment]
补充，查看Log，有对应的纪录

```
Sep 27, 2016 3:36:55 PM SEVERE coding.net.plugin.webhook.CDEventPayload$PayloadHandler parse
Payload {"zen":"Coding！ 让开发更简单","token":"xxx"}
Sep 27, 2016 3:36:55 PM INFO coding.net.plugin.subscriber.PingCDEventSubscriber onEvent
PING webhook received from repo <{"zen":"Coding！ 让开发更简单","token":"FrontEnd"}>!
```

```
Sep 27, 2016 4:11:22 PM SEVERE coding.net.plugin.webhook.CDEventHeader$PayloadHandler parse
push webhook header
Sep 27, 2016 4:11:22 PM SEVERE coding.net.plugin.webhook.CDEventPayload$PayloadHandler parse
Payload {"ref":"refs/heads/test", ...}
Sep 27, 2016 4:11:22 PM INFO coding.net.plugin.subscriber.PushCDEventSubscriber onEvent
PUSH webhook received from repo <{"ref":"refs/heads/test",...}>!
```

紧接着有一句

```
Sep 27, 2016 4:11:22 PM SEVERE coding.net.plugin.subscriber.PushCDEventSubscriber onEvent
PUSH webhook error !
```

但是没有详细信息

**Comment by yuzd** [comment]
已收到你的问题 稍等  我一会看下。。

**Comment by SunHuawei** [comment]
解决了，`Coding.Net Acess Credential`配置错误。
我本来以为是我的coding平台的授权信息。看了下代码才知道是Jenkins的授权信息。

**Comment by yuzd** [comment]
恩。需要用到jenkins的授权信息。

**Comment by SunHuawei** [comment]
另外我在调试过程中发现一些小问题
类PushCDEventSubscriber中
1. 目录分隔符固定用'\'
2. `jobSpace`拼接多出一个目录分隔符
3. 日志里会打印出敏感信息，比如密码
4. 异常被吞

**Comment by yuzd** [comment]
感谢提出的几点，我会尽快修改掉

**Comment by yuzd** [comment]
已改！请从 http://note.youdao.com/share/?id=1e5fdecbd76df84e7f4122f1e21e7129&type=note#/ 下载version1.1版本
