### ISSUE TITLE
您好，我按照配置但是报错HTTP/1.1 403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [yuzd/coding.net#3]
已经在系统配置中配置了jenkins的账号和密码，没有填成coding的账号密码。但是不知道为什么一直报这个错误
![image](https://cloud.githubusercontent.com/assets/8020726/19212653/5333ad5a-8d88-11e6-9c82-63afa60f5a39.png)

**Comment by liuhuapiaoyuan** [comment]
唔 原来要关闭 防止跨站点请求伪造  抱歉~~

**Comment by pfei-yu** [comment]
请问这个怎么关闭？
