### ISSUE TITLE
现在关闭防止跨站请求伪造会有安全提示

### ISSUE THREAD

**Issue by oldcai** [yuzd/coding.net#5]
请问如何避免安全问题的同时又能使用您的插件，
之前一个版本服务器被入侵了，
https://jenkins.io/security/advisory/2017-04-26/
按照安全建议，关闭可能会导致问题。

**Comment by yuzd** [comment]
好的 我会尽快解决这个问题

**Comment by yuzd** [comment]
还是有点问题，待解决

**Comment by yuzd** [comment]
已解决了 1.4版本 开启或不开启防止跨域请求伪造都没问题了
