### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by bolord** [yuzd/coding.net#7]
```
SEVERE coding.net.plugin.subscriber.PushCDEventSubscriber onEvent
PUSH webhook error :<java.io.IOException: remote build fail, wrong response code 403>!
```

必须要开启匿名读才能成功，系统设置里也是填的jenkins的用户
![image](https://cloud.githubusercontent.com/assets/1539763/26417418/b80cb390-40eb-11e7-8528-9459d6be64fd.png)

**Comment by yuzd** [comment]
是的 我正在怎么如何直接调用jenkins的内部api 直接build 不需要通过用户名和密码

**Comment by yuzd** [comment]
已解决了 我在生产验证过了没问题了
