### ISSUE TITLE
Merge不会触发构建

### ISSUE THREAD

**Issue by deepsadness11** [yuzd/coding.net#8]
关闭了push的webhook，只保留mr/pr，webhook发送成功，没有触发构建。能将merge的hook也触发请求吗？

**Comment by yuzd** [comment]
可以的 我搞一下

**Comment by deepsadness11** [comment]
太棒了。谢谢

**Comment by yuzd** [comment]
改好了 请使用心得version 1.5 的  hpi文件试试
